package com.amu.mappers;

import com.amu.Entities.ProdInfo;
import com.amu.Entities.ProdInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProdInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    long countByExample(ProdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    int deleteByExample(ProdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    int insert(ProdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    int insertSelective(ProdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    List<ProdInfo> selectByExample(ProdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProdInfo record, @Param("example") ProdInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    int updateByExample(@Param("record") ProdInfo record, @Param("example") ProdInfoExample example);
}