package com.amu.Entities;

import java.util.Date;

public class ProdInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.prod_id
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    private Byte prod_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.prod_name
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    private String prod_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.prod_price
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    private Byte prod_price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.prod_click
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    private Byte prod_click;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.prod_addtime
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    private Date prod_addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.prod_stock
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    private Byte prod_stock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.prod_id
     *
     * @return the value of product.prod_id
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public Byte getProd_id() {
        return prod_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.prod_id
     *
     * @param prod_id the value for product.prod_id
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public void setProd_id(Byte prod_id) {
        this.prod_id = prod_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.prod_name
     *
     * @return the value of product.prod_name
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public String getProd_name() {
        return prod_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.prod_name
     *
     * @param prod_name the value for product.prod_name
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public void setProd_name(String prod_name) {
        this.prod_name = prod_name == null ? null : prod_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.prod_price
     *
     * @return the value of product.prod_price
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public Byte getProd_price() {
        return prod_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.prod_price
     *
     * @param prod_price the value for product.prod_price
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public void setProd_price(Byte prod_price) {
        this.prod_price = prod_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.prod_click
     *
     * @return the value of product.prod_click
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public Byte getProd_click() {
        return prod_click;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.prod_click
     *
     * @param prod_click the value for product.prod_click
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public void setProd_click(Byte prod_click) {
        this.prod_click = prod_click;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.prod_addtime
     *
     * @return the value of product.prod_addtime
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public Date getProd_addtime() {
        return prod_addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.prod_addtime
     *
     * @param prod_addtime the value for product.prod_addtime
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public void setProd_addtime(Date prod_addtime) {
        this.prod_addtime = prod_addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.prod_stock
     *
     * @return the value of product.prod_stock
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public Byte getProd_stock() {
        return prod_stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.prod_stock
     *
     * @param prod_stock the value for product.prod_stock
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public void setProd_stock(Byte prod_stock) {
        this.prod_stock = prod_stock;
    }
}