package com.amu.Entities;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ProdInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public ProdInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andProd_idIsNull() {
            addCriterion("prod_id is null");
            return (Criteria) this;
        }

        public Criteria andProd_idIsNotNull() {
            addCriterion("prod_id is not null");
            return (Criteria) this;
        }

        public Criteria andProd_idEqualTo(Byte value) {
            addCriterion("prod_id =", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idNotEqualTo(Byte value) {
            addCriterion("prod_id <>", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idGreaterThan(Byte value) {
            addCriterion("prod_id >", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idGreaterThanOrEqualTo(Byte value) {
            addCriterion("prod_id >=", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idLessThan(Byte value) {
            addCriterion("prod_id <", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idLessThanOrEqualTo(Byte value) {
            addCriterion("prod_id <=", value, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idIn(List<Byte> values) {
            addCriterion("prod_id in", values, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idNotIn(List<Byte> values) {
            addCriterion("prod_id not in", values, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idBetween(Byte value1, Byte value2) {
            addCriterion("prod_id between", value1, value2, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_idNotBetween(Byte value1, Byte value2) {
            addCriterion("prod_id not between", value1, value2, "prod_id");
            return (Criteria) this;
        }

        public Criteria andProd_nameIsNull() {
            addCriterion("prod_name is null");
            return (Criteria) this;
        }

        public Criteria andProd_nameIsNotNull() {
            addCriterion("prod_name is not null");
            return (Criteria) this;
        }

        public Criteria andProd_nameEqualTo(String value) {
            addCriterion("prod_name =", value, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameNotEqualTo(String value) {
            addCriterion("prod_name <>", value, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameGreaterThan(String value) {
            addCriterion("prod_name >", value, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameGreaterThanOrEqualTo(String value) {
            addCriterion("prod_name >=", value, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameLessThan(String value) {
            addCriterion("prod_name <", value, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameLessThanOrEqualTo(String value) {
            addCriterion("prod_name <=", value, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameLike(String value) {
            addCriterion("prod_name like", value, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameNotLike(String value) {
            addCriterion("prod_name not like", value, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameIn(List<String> values) {
            addCriterion("prod_name in", values, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameNotIn(List<String> values) {
            addCriterion("prod_name not in", values, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameBetween(String value1, String value2) {
            addCriterion("prod_name between", value1, value2, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_nameNotBetween(String value1, String value2) {
            addCriterion("prod_name not between", value1, value2, "prod_name");
            return (Criteria) this;
        }

        public Criteria andProd_priceIsNull() {
            addCriterion("prod_price is null");
            return (Criteria) this;
        }

        public Criteria andProd_priceIsNotNull() {
            addCriterion("prod_price is not null");
            return (Criteria) this;
        }

        public Criteria andProd_priceEqualTo(Byte value) {
            addCriterion("prod_price =", value, "prod_price");
            return (Criteria) this;
        }

        public Criteria andProd_priceNotEqualTo(Byte value) {
            addCriterion("prod_price <>", value, "prod_price");
            return (Criteria) this;
        }

        public Criteria andProd_priceGreaterThan(Byte value) {
            addCriterion("prod_price >", value, "prod_price");
            return (Criteria) this;
        }

        public Criteria andProd_priceGreaterThanOrEqualTo(Byte value) {
            addCriterion("prod_price >=", value, "prod_price");
            return (Criteria) this;
        }

        public Criteria andProd_priceLessThan(Byte value) {
            addCriterion("prod_price <", value, "prod_price");
            return (Criteria) this;
        }

        public Criteria andProd_priceLessThanOrEqualTo(Byte value) {
            addCriterion("prod_price <=", value, "prod_price");
            return (Criteria) this;
        }

        public Criteria andProd_priceIn(List<Byte> values) {
            addCriterion("prod_price in", values, "prod_price");
            return (Criteria) this;
        }

        public Criteria andProd_priceNotIn(List<Byte> values) {
            addCriterion("prod_price not in", values, "prod_price");
            return (Criteria) this;
        }

        public Criteria andProd_priceBetween(Byte value1, Byte value2) {
            addCriterion("prod_price between", value1, value2, "prod_price");
            return (Criteria) this;
        }

        public Criteria andProd_priceNotBetween(Byte value1, Byte value2) {
            addCriterion("prod_price not between", value1, value2, "prod_price");
            return (Criteria) this;
        }

        public Criteria andProd_clickIsNull() {
            addCriterion("prod_click is null");
            return (Criteria) this;
        }

        public Criteria andProd_clickIsNotNull() {
            addCriterion("prod_click is not null");
            return (Criteria) this;
        }

        public Criteria andProd_clickEqualTo(Byte value) {
            addCriterion("prod_click =", value, "prod_click");
            return (Criteria) this;
        }

        public Criteria andProd_clickNotEqualTo(Byte value) {
            addCriterion("prod_click <>", value, "prod_click");
            return (Criteria) this;
        }

        public Criteria andProd_clickGreaterThan(Byte value) {
            addCriterion("prod_click >", value, "prod_click");
            return (Criteria) this;
        }

        public Criteria andProd_clickGreaterThanOrEqualTo(Byte value) {
            addCriterion("prod_click >=", value, "prod_click");
            return (Criteria) this;
        }

        public Criteria andProd_clickLessThan(Byte value) {
            addCriterion("prod_click <", value, "prod_click");
            return (Criteria) this;
        }

        public Criteria andProd_clickLessThanOrEqualTo(Byte value) {
            addCriterion("prod_click <=", value, "prod_click");
            return (Criteria) this;
        }

        public Criteria andProd_clickIn(List<Byte> values) {
            addCriterion("prod_click in", values, "prod_click");
            return (Criteria) this;
        }

        public Criteria andProd_clickNotIn(List<Byte> values) {
            addCriterion("prod_click not in", values, "prod_click");
            return (Criteria) this;
        }

        public Criteria andProd_clickBetween(Byte value1, Byte value2) {
            addCriterion("prod_click between", value1, value2, "prod_click");
            return (Criteria) this;
        }

        public Criteria andProd_clickNotBetween(Byte value1, Byte value2) {
            addCriterion("prod_click not between", value1, value2, "prod_click");
            return (Criteria) this;
        }

        public Criteria andProd_addtimeIsNull() {
            addCriterion("prod_addtime is null");
            return (Criteria) this;
        }

        public Criteria andProd_addtimeIsNotNull() {
            addCriterion("prod_addtime is not null");
            return (Criteria) this;
        }

        public Criteria andProd_addtimeEqualTo(Date value) {
            addCriterionForJDBCDate("prod_addtime =", value, "prod_addtime");
            return (Criteria) this;
        }

        public Criteria andProd_addtimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("prod_addtime <>", value, "prod_addtime");
            return (Criteria) this;
        }

        public Criteria andProd_addtimeGreaterThan(Date value) {
            addCriterionForJDBCDate("prod_addtime >", value, "prod_addtime");
            return (Criteria) this;
        }

        public Criteria andProd_addtimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("prod_addtime >=", value, "prod_addtime");
            return (Criteria) this;
        }

        public Criteria andProd_addtimeLessThan(Date value) {
            addCriterionForJDBCDate("prod_addtime <", value, "prod_addtime");
            return (Criteria) this;
        }

        public Criteria andProd_addtimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("prod_addtime <=", value, "prod_addtime");
            return (Criteria) this;
        }

        public Criteria andProd_addtimeIn(List<Date> values) {
            addCriterionForJDBCDate("prod_addtime in", values, "prod_addtime");
            return (Criteria) this;
        }

        public Criteria andProd_addtimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("prod_addtime not in", values, "prod_addtime");
            return (Criteria) this;
        }

        public Criteria andProd_addtimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("prod_addtime between", value1, value2, "prod_addtime");
            return (Criteria) this;
        }

        public Criteria andProd_addtimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("prod_addtime not between", value1, value2, "prod_addtime");
            return (Criteria) this;
        }

        public Criteria andProd_stockIsNull() {
            addCriterion("prod_stock is null");
            return (Criteria) this;
        }

        public Criteria andProd_stockIsNotNull() {
            addCriterion("prod_stock is not null");
            return (Criteria) this;
        }

        public Criteria andProd_stockEqualTo(Byte value) {
            addCriterion("prod_stock =", value, "prod_stock");
            return (Criteria) this;
        }

        public Criteria andProd_stockNotEqualTo(Byte value) {
            addCriterion("prod_stock <>", value, "prod_stock");
            return (Criteria) this;
        }

        public Criteria andProd_stockGreaterThan(Byte value) {
            addCriterion("prod_stock >", value, "prod_stock");
            return (Criteria) this;
        }

        public Criteria andProd_stockGreaterThanOrEqualTo(Byte value) {
            addCriterion("prod_stock >=", value, "prod_stock");
            return (Criteria) this;
        }

        public Criteria andProd_stockLessThan(Byte value) {
            addCriterion("prod_stock <", value, "prod_stock");
            return (Criteria) this;
        }

        public Criteria andProd_stockLessThanOrEqualTo(Byte value) {
            addCriterion("prod_stock <=", value, "prod_stock");
            return (Criteria) this;
        }

        public Criteria andProd_stockIn(List<Byte> values) {
            addCriterion("prod_stock in", values, "prod_stock");
            return (Criteria) this;
        }

        public Criteria andProd_stockNotIn(List<Byte> values) {
            addCriterion("prod_stock not in", values, "prod_stock");
            return (Criteria) this;
        }

        public Criteria andProd_stockBetween(Byte value1, Byte value2) {
            addCriterion("prod_stock between", value1, value2, "prod_stock");
            return (Criteria) this;
        }

        public Criteria andProd_stockNotBetween(Byte value1, Byte value2) {
            addCriterion("prod_stock not between", value1, value2, "prod_stock");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated do_not_delete_during_merge Sun Mar 10 17:43:53 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Sun Mar 10 17:43:53 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}